### ISSUE TITLE
AuthenticationMiddleware was called already panic

### ISSUE THREAD

**Issue by dneuhaeuser-zalando** [actix/actix-extras#10]
We are observing that our actix-web application occasionally panics under a lot of contention with the message "AuthenticationMiddleware was called already". This seems to come from here https://github.com/actix/actix-web-httpauth/blob/v0.4.0/src/middleware.rs#L184

We have recently migrated to actix-web 2.0 and actix-web-httpauth 0.4. We haven't observed this before the migration.

As this doesn't happen for all requests, there seems to be some race condition either within actix-web or actix-web-httpauth that causes this.

We use bearer token authorization and within the validation function, to validate the token, we just perform an HTTP request with reqwest and depending on the result return Ok or Err.

**Comment by stiiifff** [comment]
@dneuhaeuser-zalando Do you use a blocking operation in one of your handlers ?
I had the same issue and it came from the fact I was using the `web::block` helper function from actix-web in an async handler ...

**Comment by dneuhaeuser-zalando** [comment]
Yes and no. We don't use `web::block`. However we are performing database queries with diesel and those are of course blocking. (Not ideal, I know. We should change it at some point.)

**Comment by robjtede** [comment]
@dneuhaeuser-zalando can you provide us with a minimal reproduction program so we can trace the cause of the panic.

To be clear, web::block is non-blocking; its purpose is to *run* blocking code asynchronously on a background thread pool.

**Comment by stiiifff** [comment]
@robjtede re. web::blocking being non-blocking, that was my understanding ... but its use somehow lead to panics described in this issue. It would happen **systematically** if just 2 requests would arrive in //. I replaced the use of web::block by an `async move { ... }` block and no more panics. For testing, I simply used apache bench (e.g. `ab -c 10 -n 100 http://127.0.0.1:8080/).

**Comment by boydjohnson** [comment]
It looks to be inherent in the contract between `poll_ready` and `call`. The implementation of `Service` in actix-web-httpauth assumes that `poll_ready` and `call` won't be called at the same time: https://github.com/actix/actix-extras/blob/6b5215d43995af3a8eacc8505738cd689dd54833/actix-web-httpauth/src/middleware.rs#L183-L185

This doesn't seem to be true given the comments on `Service`: 
https://github.com/actix/actix-net/blob/a5c185e80e56d44ea88b4485729abdefb08b1c2a/actix-service/src/lib.rs#L95

This repo has code that reproduces the panic: https://github.com/boydjohnson/actix-example.

I have a commit that uses the `futures::lock::Mutex` that wraps the service and first calls `poll` on the lock and then `poll_ready` on the service. I would make a PR if it is wanted. https://github.com/boydjohnson/actix-extras/commit/43f7fcf3cca5e2345963317b0c96e761707721ca

**Comment by stiiifff** [comment]
@boydjohnson Thx further looking into this, I still have some intermittent errors in my project due to this issue. I will try out your proposed fix.

**Comment by boydjohnson** [comment]
I have had good luck with [debug-2 branch](github.com/boydjohnson/actix-extras/tree/debug-2) for about a month without a panic and without a deadlock. I am going to make a PR with this branch today. @stiiifff did you try the debug-2 branch at github.com/boydjohnson/actix-extras?

**Comment by boydjohnson** [comment]
Here is the backtrace of the panic with debug symbols on.

```
thread 'actix-rt:worker:0' panicked at 'AuthenticationMiddleware was called already', /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-httpauth-0.4.1/src/middleware.rs:182:9
stack backtrace:
thread 'actix-rt:worker:3' panicked at 'AuthenticationMiddleware was called already', /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-httpauth-0.4.1/src/middleware.rs:182:9
thread 'actix-rt:worker:1' panicked at 'AuthenticationMiddleware was called already', /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-httpauth-0.4.1/src/middleware.rs:182:9
   0:     0x55e81447c9a4 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55e81447c9a4 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55e81447c9a4 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55e81447c9a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55e8144994cc - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55e814476743 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:     0x55e81447f195 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55e81447f195 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55e81447f195 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:     0x55e81447eee2 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:     0x55e81447f7f2 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:     0x55e81447f3db - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x55e814498841 - core::panicking::panic_fmt::h2c05f81b567d1861
                               at src/libcore/panicking.rs:85
  13:     0x55e8144985d3 - core::option::expect_failed::h2a6d9c64cc13d139
                               at src/libcore/option.rs:1203
  14:     0x55e813ee1a7d - core::option::Option<T>::expect::h337527df1b7cc1ec
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/option.rs:347
  15:     0x55e813ec938a - <actix_web_httpauth::middleware::AuthenticationMiddleware<S,F,T> as actix_service::Service>::poll_ready::hc9467f5645ff8eb4
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-httpauth-0.4.1/src/middleware.rs:182
  16:     0x55e813e9e77a - <actix_web::app_service::AppInitService<T,B> as actix_service::Service>::poll_ready::h68fba4607aa8b7f5
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/app_service.rs:227
  17:     0x55e813ee579e - <actix_http::cloneable::CloneableService<T> as actix_service::Service>::poll_ready::hf70e719c9f503ce2
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/cloneable.rs:36
  18:     0x55e813ef61a9 - <actix_http::service::HttpServiceHandler<T,S,B,X,U> as actix_service::Service>::poll_ready::h8c0ceaabe095cf8b
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:514
  19:     0x55e813ecf2da - <actix_service::and_then::AndThenService<A,B> as actix_service::Service>::poll_ready::h6b05c5cea418697e
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.5/src/and_then.rs:45
  20:     0x55e813ebb3e2 - <actix_server::service::StreamService<T> as actix_service::Service>::poll_ready::h639d3d9bd73c800c
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.3/src/service.rs:72
  21:     0x55e813fe5a76 - actix_server::worker::Worker::check_readiness::hd7bc716bc7670fe8
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.3/src/worker.rs:260
  22:     0x55e813fe8180 - <actix_server::worker::Worker as core::future::future::Future>::poll::ha061780eb56966e8
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.3/src/worker.rs:452
  23:     0x55e813fc21ed - std::future::poll_with_tls_context::h2fc63ac68cbc3b4c
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/future.rs:102
  24:     0x55e813fe4ac5 - actix_server::worker::Worker::start::{{closure}}::{{closure}}::hf28f3650df6e7577
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.3/src/worker.rs:217
  25:     0x55e813fc4dab - <std::future::GenFuture<T> as core::future::future::Future>::poll::h7754f84d721f9723
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/future.rs:44
  26:     0x55e813ffd61e - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hf32c523459cac8fc
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:173
  27:     0x55e813fa400f - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h0d34c78d324df396
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/loom/std/unsafe_cell.rs:14
  28:     0x55e813ffc5d4 - tokio::runtime::task::core::Core<T,S>::poll::h5fb59cf7bbf12a6e
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:158
  29:     0x55e8140287c5 - tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::hdb1ff680fc2e8845
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:107
  30:     0x55e813f9a524 - core::ops::function::FnOnce::call_once::h6f6e0ad0ffbca381
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ops/function.rs:232
  31:     0x55e81400b42c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha876a75380077b90
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panic.rs:318
  32:     0x55e813fbb44c - std::panicking::try::do_call::ha3d7d325ac390665
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panicking.rs:303
  33:     0x55e814483b57 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  34:     0x55e813fb9db3 - std::panicking::try::h70f8c7404e7102cc
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panicking.rs:281
  35:     0x55e81400f33b - std::panic::catch_unwind::hb17617ba0a95dc97
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panic.rs:394
  36:     0x55e81402784e - tokio::runtime::task::harness::Harness<T,S>::poll::hdf41340f85c57166
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:89
  37:     0x55e813fe0a42 - tokio::runtime::task::raw::poll::h6ea26e017662fc82
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:104
  38:     0x55e8143f14cf - tokio::runtime::task::raw::RawTask::poll::hcf5ccbe543618a2b
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:66
  39:     0x55e81440ddb1 - tokio::runtime::task::Notified<S>::run::h5aac483df24b2d97
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/mod.rs:169
  40:     0x55e8143f7cbb - tokio::task::local::LocalSet::tick::{{closure}}::hed6f1ce6bcff69bb
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:406
  41:     0x55e814407542 - tokio::coop::with_budget::{{closure}}::h6f67a9aa7d8532e9
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:127
  42:     0x55e8143f2d88 - std::thread::local::LocalKey<T>::try_with::h8e98f69cd0a024ff
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/local.rs:262
  43:     0x55e8143f2145 - std::thread::local::LocalKey<T>::with::hb279dd3d9342de94
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/local.rs:239
  44:     0x55e8143f7c15 - tokio::coop::with_budget::h1b1d1af811a87c5d
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:120
  45:     0x55e8143f7c15 - tokio::coop::budget::h05b183cf60c574c4
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:96
  46:     0x55e8143f7c15 - tokio::task::local::LocalSet::tick::h76cfc5895da6b86a
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:406
  47:     0x55e8142cb9f4 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}::h389e8c888ef38b50
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:530
  48:     0x55e8142c56e1 - tokio::macros::scoped_tls::ScopedKey<T>::set::h0d366276f11f456c
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/macros/scoped_tls.rs:63
  49:     0x55e8142c9a42 - tokio::task::local::LocalSet::with::h36b7459acb7bee42
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:440
  50:     0x55e8142cb7a4 - <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::h963a5745ce692ee6
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:516
  51:     0x55e8142d94dd - std::future::poll_with_tls_context::h709af527744fa343
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/future.rs:102
  52:     0x55e8142c9e78 - tokio::task::local::LocalSet::run_until::{{closure}}::h70d466567ff1562e
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:390
  53:     0x55e8142dd0ff - <std::future::GenFuture<T> as core::future::future::Future>::poll::h9d17d5f3830b29d3
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/future.rs:44
  54:     0x55e8142e13a5 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}::hb6605c7f45617956
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:131
  55:     0x55e8142af5fb - tokio::coop::with_budget::{{closure}}::h703d106c447c9a5f
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:127
  56:     0x55e8142e42f5 - std::thread::local::LocalKey<T>::try_with::h8c65a46dc8c61c39
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/local.rs:262
  57:     0x55e8142e2b3e - std::thread::local::LocalKey<T>::with::he374511ebf7fa433
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/local.rs:239
  58:     0x55e8142e0249 - tokio::coop::with_budget::h9391c008680159ba
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:120
  59:     0x55e8142e0249 - tokio::coop::budget::h8549438ad4d07219
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:96
  60:     0x55e8142e0249 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::h0f529c37adb102d7
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:131
  61:     0x55e8142e1b8e - tokio::runtime::basic_scheduler::enter::{{closure}}::h18a8df24c5bb6524
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:213
  62:     0x55e8142c5822 - tokio::macros::scoped_tls::ScopedKey<T>::set::h2ae50b77b5722fc2
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/macros/scoped_tls.rs:63
  63:     0x55e8142e1a50 - tokio::runtime::basic_scheduler::enter::h80e1509c256b3d63
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:213
  64:     0x55e8142dff78 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::h79177a21f2cb7c29
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/basic_scheduler.rs:123
  65:     0x55e8142b0747 - tokio::runtime::Runtime::block_on::{{closure}}::h4e867a2346862e45
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/mod.rs:444
  66:     0x55e8142d0d14 - tokio::runtime::context::enter::hd93077b37ad16260
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/context.rs:72
  67:     0x55e8142dcc4a - tokio::runtime::handle::Handle::enter::h90813c96a8b9e3e3
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:76
  68:     0x55e8142b05b8 - tokio::runtime::Runtime::block_on::h0fdceb98e67d3a66
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/mod.rs:441
  69:     0x55e8142c9b63 - tokio::task::local::LocalSet::block_on::h1747c37aa0e2c888
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/task/local.rs:351
  70:     0x55e8142c7058 - actix_rt::runtime::Runtime::block_on::h4f51e133f7da89ff
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/runtime.rs:89
  71:     0x55e8142bdcaf - actix_rt::arbiter::Arbiter::new::{{closure}}::he3965ee835f88002
                               at /home/boydjohnson/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/arbiter.rs:137
  72:     0x55e8142cbd80 - std::sys_common::backtrace::__rust_begin_short_backtrace::h51dfab6259e8de13
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/sys_common/backtrace.rs:130
  73:     0x55e8142b1431 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hf2d9e28d0422d1af
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/mod.rs:475
  74:     0x55e8142bfb83 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h67dc90f2fed5f666
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panic.rs:318
  75:     0x55e8142ac3b4 - std::panicking::try::do_call::ha1e8b3f80e0a7a96
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panicking.rs:303
  76:     0x55e814483b57 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  77:     0x55e8142abc18 - std::panicking::try::hf706a483f17c9a30
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panicking.rs:281
  78:     0x55e8142c1253 - std::panic::catch_unwind::h454dc98ef157bb1d
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/panic.rs:394
  79:     0x55e8142b121f - std::thread::Builder::spawn_unchecked::{{closure}}::hb81b74b4f90c6963
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/thread/mod.rs:474
  80:     0x55e8142c13ff - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb0be62cedb6a6c81
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libcore/ops/function.rs:232
  81:     0x55e8144729bf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h36e46972b1b7f7b7
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  82:     0x55e814482eed - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hdde89c32ce6999de
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  83:     0x55e814482eed - std::sys_common::thread::start_thread::h5ae3fdd4dad03dd5
                               at src/libstd/sys_common/thread.rs:13
  84:     0x55e814482eed - std::sys::unix::thread::Thread::new::thread_start::h76b2403b2434c4c0
                               at src/libstd/sys/unix/thread.rs:80
  85:     0x7feb5d8246db - start_thread
  86:     0x7feb5d33588f - __clone
  87:                0x0 - <unknown>


```

**Comment by cetra3** [comment]
@dneuhaeuser-zalando There is a PR active by @boydjohnson that should address your issue.

Are you able to test that the PR solves your issue?

**Comment by stiiifff** [comment]
As mentioned in the PR, it looks good on my end as well.
